services:
  stt-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./shared_data:/app/shared_data
      - ./api/static:/app/static
      - ./output:/app/output
    depends_on:
      - redis

  stt-worker:
    build:
      context: .
      dockerfile: stt-worker/Dockerfile
    volumes:
      - ./shared_data:/app/shared_data
      - ./output:/app/output
    depends_on:
      - redis
    deploy:
      replicas: 1
    
  llm-worker:
    build:
      context: .
      dockerfile: llm-worker/Dockerfile
    volumes:
      - ./shared_data:/app/shared_data
      - ./output:/app/output
    depends_on:
      - redis
      - ollama
    deploy:
      replicas: 1

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama

  tts-worker:
    build:
      context: .
      dockerfile: tts-worker/Dockerfile
    volumes:
      - ./shared_data:/app/shared_data
      - ./output:/app/output
    depends_on:
      - redis
      - llm-worker
    deploy:
      replicas: 1
  
  redis:
    image: redis:6.2-alpine
    container_name: redis-queue
    ports:
      - "6379:6379"



