services:
  stt-api:
    build:
      context: .
      dockerfile: api/Dockerfile
      args:
        - DEVICE=${DEVICE:-cpu}
    ports:
      - "8000:8000"
    volumes:
      - ./shared_data:/app/shared_data
      - ./api/static:/app/static
      - ./output:/app/output
    depends_on:
      - stt-worker
      - llm-worker
      - tts-worker

  stt-worker:
    build:
      context: .
      dockerfile: stt-worker/Dockerfile
      args:
        - DEVICE=${DEVICE:-cpu}
    volumes:
      - ./shared_data:/app/shared_data
      - ./output:/app/output

    deploy:
      replicas: 1
    
  llm-worker:
    build:
      context: .
      dockerfile: llm-worker/Dockerfile
      args:
        - DEVICE=${DEVICE:-cpu}
    volumes:
      - ./shared_data:/app/shared_data
      - ./output:/app/output
    depends_on:
      - ollama
    deploy:
      replicas: 1

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama

  tts-worker:
    build:
      context: .
      dockerfile: tts-worker/Dockerfile
      args:
        - DEVICE=${DEVICE:-cpu}
    volumes:
      - ./shared_data:/app/shared_data
      - ./output:/app/output
    depends_on:
      - llm-worker
    deploy:
      replicas: 1
  
