# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_pb2 as voice__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in voice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class STTServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeStream = channel.stream_stream(
                '/voice.STTService/TranscribeStream',
                request_serializer=voice__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__pb2.STTEvent.FromString,
                _registered_method=True)


class STTServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def TranscribeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_STTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.TranscribeStream,
                    request_deserializer=voice__pb2.AudioChunk.FromString,
                    response_serializer=voice__pb2.STTEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice.STTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice.STTService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class STTService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice.STTService/TranscribeStream',
            voice__pb2.AudioChunk.SerializeToString,
            voice__pb2.STTEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LLMServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateStream = channel.stream_stream(
                '/voice.LLMService/GenerateStream',
                request_serializer=voice__pb2.TextChunk.SerializeToString,
                response_deserializer=voice__pb2.LLMEvent.FromString,
                _registered_method=True)


class LLMServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=voice__pb2.TextChunk.FromString,
                    response_serializer=voice__pb2.LLMEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice.LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice.LLMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LLMService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice.LLMService/GenerateStream',
            voice__pb2.TextChunk.SerializeToString,
            voice__pb2.LLMEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TTSServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SynthesizeStream = channel.stream_stream(
                '/voice.TTSService/SynthesizeStream',
                request_serializer=voice__pb2.TextChunk.SerializeToString,
                response_deserializer=voice__pb2.AudioChunk.FromString,
                _registered_method=True)


class TTSServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SynthesizeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TTSServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SynthesizeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SynthesizeStream,
                    request_deserializer=voice__pb2.TextChunk.FromString,
                    response_serializer=voice__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'voice.TTSService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('voice.TTSService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TTSService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SynthesizeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/voice.TTSService/SynthesizeStream',
            voice__pb2.TextChunk.SerializeToString,
            voice__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
