# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'voice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvoice.proto\x12\x05voice\"Z\n\nAudioChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x12\n\nend_stream\x18\x03 \x01(\x08\x12\x16\n\x0espeech_started\x18\x04 \x01(\x08\"\x80\x01\n\x08STTEvent\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x11\n\tinterrupt\x18\x04 \x01(\x08\x12\x15\n\rrestore_audio\x18\x05 \x01(\x08\x12\x16\n\x0estt_latency_ms\x18\x06 \x01(\x01\"A\n\tTextChunk\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nend_stream\x18\x03 \x01(\x08\"c\n\x08LLMEvent\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\ntext_chunk\x18\x02 \x01(\t\x12\x16\n\x0ellm_latency_ms\x18\x03 \x01(\x01\x12\x17\n\x0fstream_finished\x18\x04 \x01(\x08\x32H\n\nSTTService\x12:\n\x10TranscribeStream\x12\x11.voice.AudioChunk\x1a\x0f.voice.STTEvent(\x01\x30\x01\x32\x45\n\nLLMService\x12\x37\n\x0eGenerateStream\x12\x10.voice.TextChunk\x1a\x0f.voice.LLMEvent(\x01\x30\x01\x32I\n\nTTSService\x12;\n\x10SynthesizeStream\x12\x10.voice.TextChunk\x1a\x11.voice.AudioChunk(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=22
  _globals['_AUDIOCHUNK']._serialized_end=112
  _globals['_STTEVENT']._serialized_start=115
  _globals['_STTEVENT']._serialized_end=243
  _globals['_TEXTCHUNK']._serialized_start=245
  _globals['_TEXTCHUNK']._serialized_end=310
  _globals['_LLMEVENT']._serialized_start=312
  _globals['_LLMEVENT']._serialized_end=411
  _globals['_STTSERVICE']._serialized_start=413
  _globals['_STTSERVICE']._serialized_end=485
  _globals['_LLMSERVICE']._serialized_start=487
  _globals['_LLMSERVICE']._serialized_end=556
  _globals['_TTSSERVICE']._serialized_start=558
  _globals['_TTSSERVICE']._serialized_end=631
# @@protoc_insertion_point(module_scope)
